### ISSUE TITLE
Add more info Readme.md

### ISSUE THREAD

**Issue by NegriHenrique** [Mikael-R/readme-template-generator#1]
The main Readme is very simple, has only the title of system.

my suggestion is to amplify the readme by adding information about what the system does to make it clearer to the user. Infos like what the system does, how to use, etc.

**Comment by ademarCardoso** [comment]
@Mikael-R  I think the readme needs more information too, at the moment it doesn’t bring any relevant information, how it works, how to use it, because the idea is really cool :)

**Comment by Mikael-R** [comment]
Thanks guys, I'm working hard on the project and new features are coming soon 😊

The template I'm basing on is this: https://github.com/Mikael-R/readme-template
He will have everything he has in this template and more

**Comment by Mikael-R** [comment]
Create a stable version 💯
