### ISSUE TITLE
HELP: Breaks at home page url

### ISSUE THREAD

**Issue by sankalpmukim** [Mikael-R/readme-template-generator#5]
It is possible that I am doing something wrong but I cannot figure it out. I start it normally and at the home page url step It breaks.
![image](https://user-images.githubusercontent.com/41541375/127764984-8b0b39d6-27f1-4b94-9c85-f3ce94dcbff4.png)

**Comment by Mikael-R** [comment]
Fixed in version 0.9.13

Thanks for feedback, sorry for late
